In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

**Solution 1:**

In [11]:
# Method 1: Using np.array
array_1 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array created using np.array:\n", array_1)

Array created using np.array:
 [[1 2 3]
 [4 5 6]]


In [12]:
# Method 2: Using np.full
array_2 = np.full((2, 3), 1)
array_2[0] = [1, 2, 3]
array_2[1] = [4, 5, 6]

print("Array created using np.full:\n", array_2)

Array created using np.full:
 [[1 2 3]
 [4 5 6]]


In [13]:
# Method 3: Using np.ones and modifying values
array_3 = np.ones((2, 3), dtype=int)
array_3[0, :] = [1, 2, 3]
array_3[1, :] = [4, 5, 6]

print("Array created using np.ones and modifying values:\n", array_3)

Array created using np.ones and modifying values:
 [[1 2 3]
 [4 5 6]]


**Solution 2:**

In [4]:
# Parameters
w = 0
wR = 10
numPers = 20

# Generate an array of evenly spaced numbers
array_1d = np.linspace(w, wR, numPers)

# Reshape the array into a 2D array (for example, shape (4, 5))
array_2d = array_1d.reshape(4, 5)

print("1D array:", array_1d)
print("2D array:\n", array_2d)

1D array: [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
2D array:
 [[ 0.          0.52631579  1.05263158  1.57894737  2.10526316]
 [ 2.63157895  3.15789474  3.68421053  4.21052632  4.73684211]
 [ 5.26315789  5.78947368  6.31578947  6.84210526  7.36842105]
 [ 7.89473684  8.42105263  8.94736842  9.47368421 10.        ]]


**Solution 3:**

**a.** The difference between **'np.array'**, **'np.asarray'**, and **'np.asanyarray'**

* **'np.array':** Creates a new array from the input data. If the input is already an array, it will still create a new copy unless copy=False is specified.
* **'np.asarray':** Converts the input to an array, but does not make a copy if the input is already an array.

* **'np.asanyarray':** Similar to np.asarray, but it passes through subclasses of ndarray (like matrix).

In [5]:
a = [1, 2, 3]

array = np.array(a)
asarray = np.asarray(a)
asanyarray = np.asanyarray(a)

print("np.array:", array)
print("np.asarray:", asarray)
print("np.asanyarray:", asanyarray)

np.array: [1 2 3]
np.asarray: [1 2 3]
np.asanyarray: [1 2 3]


**b.** The difference between **Deep copy** and **shallow copy**

* **Shallow Copy:** Creates a new array object, but the elements are references to the same objects as in the original array.
* **Deep Copy:** Creates a new array object and recursively copies all objects found in the original array, creating new copies of everything.

In [8]:
import copy

original = np.array([1, 2, 3, 4])

shallow = copy.copy(original)
deep = copy.deepcopy(original)

print("Original:", original)
print("Shallow Copy:", shallow)
print("Deep Copy:", deep)


Original: [1 2 3 4]
Shallow Copy: [1 2 3 4]
Deep Copy: [1 2 3 4]


**Solution 4:**

In [9]:
# Generate a 5x5 array with random integers between 0 and 10
random_int_array = np.random.randint(0, 10, (5, 5))

# Extract all even integers
even_integers = random_int_array[random_int_array % 2 == 0]

# Extract all odd integers
odd_integers = random_int_array[random_int_array % 2 != 0]

print("Random integer array:\n", random_int_array)
print("Even integers:", even_integers)
print("Odd integers:", odd_integers)

Random integer array:
 [[2 9 5 8 7]
 [0 8 8 3 1]
 [6 7 5 6 3]
 [4 7 1 9 7]
 [5 4 4 9 2]]
Even integers: [2 8 0 8 8 6 6 4 4 4 2]
Odd integers: [9 5 7 3 1 7 5 3 7 1 9 7 5 9]


**Solution 5:**

In [10]:
# Generate a 3D array with random integers between 0 and 10
random_3d_array = np.random.randint(0, 10, (3, 3, 3))

# Find the indices of the maximum values along each depth level (third axis)
indices_max = np.argmax(random_3d_array, axis=2)

# Element-wise multiplication with another array
another_array = np.random.randint(0, 10, (3, 3, 3))
elementwise_multiplication = random_3d_array * another_array

print("3D array:\n", random_3d_array)
print("Indices of max values along each depth level:\n", indices_max)
print("Another 3D array:\n", another_array)
print("Element-wise multiplication result:\n", elementwise_multiplication)

3D array:
 [[[4 7 0]
  [9 0 4]
  [8 9 9]]

 [[9 4 2]
  [9 8 5]
  [1 3 9]]

 [[5 8 7]
  [0 3 8]
  [6 2 8]]]
Indices of max values along each depth level:
 [[1 0 1]
 [0 0 2]
 [1 2 2]]
Another 3D array:
 [[[5 0 4]
  [1 3 2]
  [1 2 1]]

 [[2 7 1]
  [9 9 0]
  [0 3 5]]

 [[0 2 5]
  [6 6 4]
  [5 5 9]]]
Element-wise multiplication result:
 [[[20  0  0]
  [ 9  0  8]
  [ 8 18  9]]

 [[18 28  2]
  [81 72  0]
  [ 0  9 45]]

 [[ 0 16 35]
  [ 0 18 32]
  [30 10 72]]]


**Solution 6:**

In [14]:
# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 0 and 10
array_3d = np.random.randint(0, 10, (3, 3, 3))

print("3D array:\n", array_3d)

3D array:
 [[[5 9 1]
  [2 5 1]
  [6 3 4]]

 [[6 8 9]
  [6 7 1]
  [2 1 8]]

 [[1 5 3]
  [3 6 4]
  [7 0 4]]]


In [15]:
# Find the indices of the maximum values along each depth level (third axis)
indices_max = np.argmax(array_3d, axis=2)

print("Indices of the maximum values along each depth level:\n", indices_max)

Indices of the maximum values along each depth level:
 [[1 1 0]
 [2 1 2]
 [1 1 0]]


In [16]:
# Create another 3D array of the same shape
another_array = np.random.randint(0, 10, (3, 3, 3))

# Perform element-wise multiplication between both arrays
elementwise_multiplication = array_3d * another_array

print("Another 3D array:\n", another_array)
print("Element-wise multiplication result:\n", elementwise_multiplication)

Another 3D array:
 [[[4 7 7]
  [4 8 3]
  [3 6 3]]

 [[6 8 4]
  [0 5 8]
  [6 6 7]]

 [[3 9 6]
  [1 2 2]
  [5 0 6]]]
Element-wise multiplication result:
 [[[20 63  7]
  [ 8 40  3]
  [18 18 12]]

 [[36 64 36]
  [ 0 35  8]
  [12  6 56]]

 [[ 3 45 18]
  [ 3 12  8]
  [35  0 24]]]


## **EDA**

In [2]:
df = pd.read_csv(r"E:\Python Programming\learning\lectures\Python libraries\files\People_data.csv")
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [3]:
df.drop('Index', axis=1, inplace=True)
df

User Id First Name Last Name  Gender  \
0    8717bbf45cCDbEe     Shelia   Mahoney    Male   
1    3d5AD30A4cD38ed         Jo    Rivers  Female   
2    810Ce0F276Badec     Sheryl    Lowery  Female   
3    BF2a889C00f0cE1    Whitney    Hooper    Male   
4    9afFEafAe1CBBB9    Lindsey      Rice  Female   
..               ...        ...       ...     ...   
995  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996  ECddaFEDdEc4FAB      Donna     Barry  Female   
997  2adde51d8B8979E      Cathy  Mckinney  Female   
998  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 9 columns]

**Solution 7:**

In [ ]:
df.Phone