**Problem 1:** What is Python library? Why do we use Python libraries?

**Answer:** A Python library is collection of reable Python functions and methods bundled together, serving different purposed and making Python a versatile
for various programming tasks. We use Python libraries to promote code reuse, save time and effort, and improve efficiency by providing access to pre-written and tested code for specific functions or tasks. They allow for better organization, easier debug, and increased readability of your code, and are an essential part of Python programming. 

**Problem 2:** What is the difference between Numpy array and List?

**Answer:** A numpy array and list are both data structures in Python, but they have some key differences:

 1. *Data type:* A numpy array can contian elements of the same data type, while a list can contain elements of the different data types.

 2. *Memory Allocation:* Numpy arrays are more memory efficient than lists. They use less memory because they store data in a contiguous block of memory, and they can store large amounts of data in small memory footprint.

 3. *Speed:* Numpy arrays are faster than list for mathematical operations. This is because numpy arrays are implemented in C, which is a compiled language, and they can perfors operations on entire arrays at once, which is not possible with lists.

 4. *Functionality:* Numpy arrays have more advanced functionality for mathematical operations and manipulation. They have built in functions for operations like slicing, indexing, reshaping, and broadcasting, which are not available in lists.

**Problem 3:** Find the shape, size and dimension of the following array?

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [3]:
import numpy as np  # Import numpy from python library 

# We have given array:
given_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Given array:\n", given_arr, "\n")

print("Shape:", given_arr.shape, end='\n')  # Calculating shape of the given_arr
print("Size:", given_arr.size, end='\n')    # Calculating size of the given_arr
print("Dimension:", given_arr.shape)         # Calculating dimension of the given_arr

Given array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Shape: (3, 4)
Size: 12
Dimension: (3, 4)


**Problem 4:** Write python code to access the first row of the following array?

**Solution:**

In [28]:
# Given array:
given_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Given array:\n", given_arr, "\n")

# Accsing first row of the given_arr using indexing method
print("First row:", given_arr[0])

Given array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

First row: [1 2 3 4]


**Problem 5:** How do you access the element at the third row and fourth column from the given numpy array?

**Solution:** We can access the element at the third row and fourth column from the given numpy array using indexing method.

In [27]:
# Example:

# Given array:
given_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Given array:\n", given_arr, "\n")

# Accessing element at 3rd row and 4th column, using indexing method.
print("Element at 3rd row and 4th column:", given_arr[2][3])

Given array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Element at 3rd row and 4th column: 12


**Problem 6:** Write code to extract all odd-indexed elements from the given numpy array?

**Solution:**

In [4]:
# Given array:
given_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Given array:\n", given_arr, "\n")

# Extracting all odd-indexed elements from the given numpy array, using indexing and slicing method
odd_indexed_elements = given_arr[:, 1::2]
print("Odd indexed elements:\n", odd_indexed_elements)


Given array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Odd indexed elements:
 [[ 2  4]
 [ 6  8]
 [10 12]]


**Problem 7:** How can you generate a random 3x3 matrix with values between 0 and 1?

**Solution:** We can use the following code to generate a random 3x3 matrix with values between 0 and 1.

In [29]:
# Generating 3x3 matrix with values between 0 and 1
matrix = np.random.rand(3, 3)

# Print the generated matrix
print(matrix)

[[0.83026085 0.47807824 0.48496666]
 [0.26723115 0.25425173 0.70674668]
 [0.6552762  0.92758364 0.4131714 ]]


**Problem 8:** Describe the difference between np.random.rand and np.randn?

**Solution:** The functions 'np.random.rand' and 'np.random.randn' Python's Numpy library both generate random values, but they differ in their distribution and purpose.

* np.random.rand generated random values from a distribution over the interval '[0, 1)'. It takes one or more arguments specifying the shape of the output array, and returns an array of the given shape filled with random values.

* Here's an example:

In [30]:
arr = np.random.rand(4, 4)
print(arr)

[[0.34017584 0.42222098 0.23103121 0.7174268 ]
 [0.82836461 0.2257545  0.76307667 0.62028884]
 [0.49967161 0.74687219 0.47634287 0.14526647]
 [0.2458038  0.94342014 0.2075926  0.34751249]]


* np.random.randn' generates random values from a standard normal distribution (also known as Gaussian distribution), which has a mean of 0 and a standard deviation of 1. It also taked one or more arguments specifying the shape of the output array, and returns an array of the given shape filled with random values.

* Here's an example:

In [32]:
arr = np.random.randn(3, 4)
print(arr)

[[ 1.42702033 -0.33421309 -1.72848106  1.23271988]
 [ 0.05092147  0.21517289  0.77872809 -1.23920304]
 [-0.40219057 -0.00970809  0.21040912  1.39313101]]


**Problem 9:** Write code to increase the dimension of the following array?

**Solution:**

In [40]:
# Given array
given_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Before expanding dimesion:\n", given_arr, "\n")

# Expanding dimension using 'expand_dims()' function from numpy library
expand_dims = np.expand_dims(given_arr, axis=0)
print("After expanding dimension:\n", expand_dims)


Before expanding dimesion:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

After expanding dimension:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


**Problem 10:** How to transpose the following array in Numpy?

**Solution:**

In [42]:
# Given array
given_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Before transpose:\n", given_arr, "\n")

# Transpose the given array using 'T' method
transpose_arr = given_arr.T
print("After transpose:\n", transpose_arr)

Before transpose:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

After transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Problem 11.** Consider the following matrix:

* matrixA = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
* matrixB = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

**Perform the following operation using Python:
 1. Index wise multiplication
 2. Matrix multiplication
 3. Add both the matrics
 4. Substract matrix B from A
 5. Divide Matrix B by A

**Solution:**

In [4]:
# Given matrics
matrixA = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [56]:
# Performing index wise multiplication
result = matrixA * matrixB
print(result)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [93]:
# Performing matrix multiplication

cols_matrixA = matrixA[0].size  # Calculating total column of matrixA
rows_matrixB = matrixB.shape[0] # Calculating total rows of matrixB

# matrixA @ matrixB, possible if total column of matrixA == total rows of matrixB
if cols_matrixA == rows_matrixB:
    result = matrixA @ matrixB
    print(result)
else:
    print("result: Not possible")

result: Not possible


In [94]:
# Performing matrics addition
result = matrixA + matrixB
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [5]:
# Substracting matrixB from matrixA
result = matrixA - matrixB
print(result)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [96]:
# Divide matrixB by matrixA
result = matrixB / matrixA
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Problem 12:** Which function in Numpy can be used to swap the byte order of an array?

**Solution:** The numpy.byteswap() function can be used to swap the byte order of an array. It returns a new array with the bytes of each element swapped. The syntax of the numpy.byteswap() function is as follows:
* *numpy.byteswap(arr)*

Here's an example of how to use the 'numpy.ndarray.byteswap' function:

In [20]:
# Create a Numpy array
arr = np.array([1, 2, 3, 14])

# Print the byte order of the array
print("Original byte order:", arr.dtype.byteorder)

# Swap the byte order of hte array
arr = arr.byteswap()

# Print the byte order of the array after swapping
print("Byte order after swapping:", arr.dtype.byteorder)

Original byte order: =
Byte order after swapping: =


**Problem 13:** What is the significance of the np.linalg.inv function?

**Solution:** The 'np.linalg.inv' function in Numpy is used to compute the multiplicative inverse of a square matrix, In linear algebra, the inverse of a matrix is crucial for solving systems of linear equations and for various other mathematical operations.

Here a brief explanation of the significance.
* *Solving Equations:* When we have a systems of linear equations (line x + y = 5 and 2x - 3y = 10) represented by a matrix (Ax = B), 'np.linalg.inv' helps find the values of variables by multiplying the inverse of matrix A with the constant matrix B.

* *Checking Invertibility:* Before finding the inverse , its crucial to checks if a matrix is invertible. 'np.linalg.inv' indirectly helps by checking if the determinant of the matrix is non-zero.

* *Eisenvalue problems:* In certain involving characteristics of systems, the inverse of a matrix is used 'np.linalg.inv' is useful in such scenarios.

* Example:

In [11]:
# Define a 2 x 2 matrix
A = np.array([[10, 20], [30, 40]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Print the inverse of A
print(A_inv)

[[-0.2   0.1 ]
 [ 0.15 -0.05]]


**Problem 14:** What does the np.reshape function do, and how is it used?

**SOlution:** The 'np.reshape' function in Numpy is used to change the shape of an array without changing its data. It returns a new array with the same data but with a different shape. The function is useful when we need to change the dimensions of an array, for example, when we want to convert a one-dimensional array into a two-dimensional array or vice versa. It can also be used to create arrays with a specific shape, such as matrices and tensors.

The syntax of the 'np.reshape' function is 'numpy.reshape(a, newshape, order='c), were 'a' is the array to be reshaped, 'newshape' is desired shape of the new array, and 'order' is the order of the elements in the new array. The 'newshape' argument can be a tuple or a list of integers.

Here are some examples of how to use the 'np.reshape' function:

In [13]:
# Reshaping a 2D Numpy array

arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
reshaped = np.reshape(arr_2D, (3, 4))
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# Reshaping a Numpy array using a variable and an inferred dimension

arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
reshaped = np.reshape(arr_2D, (3, -1))
print(reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Problem 15:** What is broadcasting in Numpy?

**Solution:** In Numpy, broadcasting refers to the ability to perform element-wise operations on arrays of different shapes and sizes. Numpy automatically adjust the dimensions of smaller array to match the larger one, making it possible to perform operations without explicity reshaping the arrays. This simplifies code and improves efficiency in array operations.

Examples:

In [6]:
# Broadcasting between a 1D array and a scalar value:

a = np.array([1, 2, 3])
b = 2
result = a + b
print(result)

[3 4 5]


In [10]:
# Broadcasting between a 2D arrays:

a = np.array([[1, 2, 3]])
b = np.array([[2, 2, 4], [3, 3, 2], [4, 4, 4]])
result = a + b
print(result)

[[3 4 7]
 [4 5 5]
 [5 6 7]]
